// 仅保留包内布局/排版样式；控件外观一律取自 dsh-tauri-ui/client。
import { cssr } from 'dsh-tauri-ui/client'

const { c } = cssr

export default c([
  c(`.dshp-session__page`, {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    minHeight: '100%',
    color: 'var(--dsw-alias-label-primary)',
  }),
  c(`.dshp-session__header`, {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  }),
  c(`.dshp-session__title`, {
    margin: 0,
    fontSize: '24px',
    lineHeight: '32px',
    fontWeight: 600,
  }),
  c(`.dshp-session__toolbar`, {
    position: 'sticky',
    top: 0,
    zIndex: 2,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
    padding: '8px 0',
    background: 'var(--dsw-alias-bg-base, var(--dsw-alias-bg-module-platform))',
  }),
  c(`.dshp-session__search`, {
    flex: '1 1 220px',
    minWidth: 0,
  }),
  c(`.dshp-session__menu-select`, {
    maxWidth: '220px',
    minWidth: 0,
  }),
  c(`.dshp-session__menu-select-label`, {
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    minWidth: 0,
  }),
  c(`.dshp-session__groups`, {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  }),
  c(`.dshp-session__group`, {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  }),
  c(`.dshp-session__group-header`, {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '0 2px',
    color: 'var(--dsw-alias-label-secondary)',
  }),
  c(`.dshp-session__group-title`, {
    fontSize: '14px',
    lineHeight: '22px',
    fontWeight: 500,
    color: 'var(--dsw-alias-label-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  c(`.dshp-session__group-count`, {
    fontSize: '13px',
    lineHeight: '20px',
    color: 'var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary))',
    marginLeft: 'auto',
  }),
  c(`.dshp-session__list`, {
    display: 'flex',
    flexDirection: 'column',
    margin: 0,
    padding: 0,
    listStyle: 'none',
    border: '1px solid var(--dsw-alias-border-weak, rgba(127,127,127,0.2))',
    borderRadius: '12px',
    overflow: 'hidden',
  }),
  c(`.dshp-session__row`, {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    boxSizing: 'border-box',
    padding: '14px 16px',
    background: 'var(--dsw-alias-bg-base)',
    minHeight: '64px',
  }, [
    c('& + &', { borderTop: '1px solid var(--dsw-alias-border-weak, rgba(127,127,127,0.2))' }),
  ]),
  c(`.dshp-session__row-main`, {
    flex: '1 1 auto',
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  }),
  c(`.dshp-session__row-title`, {
    fontSize: '13px',
    lineHeight: '22px',
    color: 'var(--dsw-alias-label-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    padding: 0,
    border: 'none',
    background: 'none',
    fontFamily: 'inherit',
    textAlign: 'left',
    cursor: 'default',
    maxWidth: '100%',
  }, [
    c('&:hover', {
      cursor: 'pointer',
      textDecoration: 'underline',
      textUnderlineOffset: '2px',
      textDecorationColor: 'var(--dsw-alias-label-secondary, currentColor)',
    }),
  ]),
  c(`.dshp-session__row-time`, {
    fontSize: '13px',
    lineHeight: '20px',
    color: 'var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary))',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  c(`.dshp-session__row-actions`, {
    flex: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  }),
  c(`.dshp-session__empty`, {
    padding: '32px 0',
    textAlign: 'center',
    fontSize: '14px',
    lineHeight: '22px',
    color: 'var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary))',
  }),
  c(`.dshp-session__error`, {
    padding: '12px 16px',
    borderRadius: '10px',
    background: 'var(--dsw-alias-interactive-bg-hover, rgba(127,127,127,0.08))',
    color: 'var(--dsw-alias-state-error-primary, var(--dsw-alias-danger-text, var(--dsw-alias-label-primary)))',
    fontSize: '13px',
    lineHeight: '20px',
  }),
])
