import { styles as sharedStyles } from '../constants/theme'
import { cssr } from '../utils/cssr'

const { c, bem: { b, e, m } } = cssr
const { dimmed, error, focusRing, hover, primary, secondary, tertiary } = sharedStyles
export default b('goal-bar', {
  'position': 'relative',
  'isolation': 'isolate',
  'boxSizing': 'border-box',
  'display': 'flex',
  'alignItems': 'center',
  'gap': '10px',
  'width': '100%',
  'maxWidth': 'calc(var(--dsh-composer-card-max-width) - 4 * var(--dsh-composer-dock-inset))',
  'height': '36px',
  'margin': '0 auto',
  'padding': '4px 5px 4px 12px',
  'border': '0',
  '--dsw-elevation-stroke-color': 'var(--dsw-alias-border-l1)',
  'borderRadius': '12px',
  'boxShadow': 'var(--dsw-elevation-panel)',
}, [
  c('&::before', {
    content: '""',
    position: 'absolute',
    inset: '0',
    zIndex: '-1',
    borderRadius: 'inherit',
    background: 'var(--dsw-specific-menu)',
    backdropFilter: 'var(--dsw-menu-backdrop-filter)',
    pointerEvents: 'none',
  }),
  e('glyph', {
    display: 'inline-flex',
    flex: 'none',
    color: tertiary,
  }),
  e('label', {
    flex: 'none',
    fontSize: '13px',
    lineHeight: '24px',
    fontWeight: '500',
    color: primary,
  }),
  e('objective', {
    flex: '1',
    minWidth: '0',
    overflow: 'hidden',
    fontSize: '13px',
    lineHeight: '20px',
    color: 'var(--dsw-alias-label-primary-dimmed, var(--dsw-alias-label-dimmed))',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  e('error', {
    flex: '1',
    minWidth: '0',
    overflow: 'hidden',
    color: error,
    fontSize: '12px',
    lineHeight: '20px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  e('actions', {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flex: 'none',
    marginLeft: 'auto',
  }),
  e('action', {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    padding: '0',
    border: '0',
    background: 'transparent',
    color: primary,
    font: 'inherit',
    fontSize: '13px',
    lineHeight: '20px',
    borderRadius: '6px',
    textDecoration: 'underline',
    textDecorationColor: 'transparent',
    textUnderlineOffset: '2px',
    transition: 'text-decoration-color 120ms ease',
    cursor: 'pointer',
  }, [
    c('&:hover:not(:disabled)', {
      textDecorationColor: 'currentcolor',
    }),
    c('&:focus-visible', { ...focusRing }),
    c('&:disabled', {
      color: dimmed,
      cursor: 'default',
      opacity: '0.4',
    }),
    m('icon', {
      width: '28px',
      height: '28px',
      padding: '0',
      border: 'none',
      borderRadius: '999px',
      cornerShape: 'round',
      background: 'transparent',
      color: tertiary,
      textDecoration: 'none',
      cursor: 'pointer',
    }, [
      c('&:hover:not(:disabled)', {
        background: hover,
        color: secondary,
      }),
      c('&:disabled', {
        color: tertiary,
        cursor: 'default',
        opacity: '0.4',
      }),
    ]),
  ]),
])
