window.NIGHTFALL_SCENES = [
  {
    id: "storm",
    title: "Storm Neon",
    landscape: "assets/storm.jpg",
    portrait: "assets/storm-p.jpg",
    thumb: "assets/storm-thumb.jpg",
    originL: "58% 40%",
    originP: "50% 36%",
    fx: "storm",
  },
  {
    id: "sakura",
    title: "Sakura Tempest",
    landscape: "assets/sakura.jpg",
    portrait: "assets/sakura-p.jpg",
    thumb: "assets/sakura-thumb.jpg",
    originL: "42% 40%",
    originP: "50% 36%",
    fx: "sakura",
  },
  {
    id: "hanabi",
    title: "Hanabi Night",
    landscape: "assets/hanabi.jpg",
    portrait: "assets/hanabi-p.jpg",
    thumb: "assets/hanabi-thumb.jpg",
    originL: "38% 46%",
    originP: "50% 40%",
    fx: "hanabi",
  },
  {
    id: "tide",
    title: "Tidebreaker",
    landscape: "assets/tide.jpg",
    portrait: "assets/tide-p.jpg",
    thumb: "assets/tide-thumb.jpg",
    originL: "44% 48%",
    originP: "50% 42%",
    fx: "tide",
  },
  {
    id: "moonlit",
    title: "Moonlit Silver",
    landscape: "assets/moonlit.jpg",
    portrait: "assets/moonlit-p.jpg",
    thumb: "assets/moonlit-thumb.jpg",
    originL: "46% 36%",
    originP: "50% 34%",
    fx: "moonlit",
  },
];
