window.WALLPAPER_SCENES = [
  {
    id: "storm",
    title: "Storm Neon",
    sub: "30fps 循环视频 · 迎风回望踏步",
    landscape: "assets/storm.jpg",
    portrait: "assets/storm-p.jpg",
    thumbL: "assets/storm-thumb.jpg",
    thumbP: "assets/storm-p-thumb.jpg",
    videoL: "assets/vid/storm-l.mp4",
    videoP: "assets/vid/storm-p.mp4",
    originL: "50% 42%",
    originP: "50% 38%",
    fx: "storm",
  },
  {
    id: "sakura",
    title: "Sakura Tempest",
    sub: "30fps 循环视频 · 回眸转身接花",
    landscape: "assets/sakura.jpg",
    portrait: "assets/sakura-p.jpg",
    thumbL: "assets/sakura-thumb.jpg",
    thumbP: "assets/sakura-p-thumb.jpg",
    videoL: "assets/vid/sakura-l.mp4",
    videoP: "assets/vid/sakura-p.mp4",
    originL: "48% 40%",
    originP: "50% 36%",
    fx: "sakura",
  },
  {
    id: "hanabi",
    title: "Hanabi Night",
    sub: "30fps 循环视频 · 抬头举臂看烟火",
    landscape: "assets/hanabi.jpg",
    portrait: "assets/hanabi-p.jpg",
    thumbL: "assets/hanabi-thumb.jpg",
    thumbP: "assets/hanabi-p-thumb.jpg",
    videoL: "assets/vid/hanabi-l.mp4",
    videoP: "assets/vid/hanabi-p.mp4",
    originL: "42% 46%",
    originP: "50% 40%",
    fx: "hanabi",
  },
  {
    id: "tide",
    title: "Tidebreaker",
    sub: "30fps 循环视频 · 挡浪看月",
    landscape: "assets/tide.jpg",
    portrait: "assets/tide-p.jpg",
    thumbL: "assets/tide-thumb.jpg",
    thumbP: "assets/tide-p-thumb.jpg",
    videoL: "assets/vid/tide-l.mp4",
    videoP: "assets/vid/tide-p.mp4",
    originL: "46% 48%",
    originP: "50% 42%",
    fx: "tide",
  },
  {
    id: "moonlit",
    title: "Moonlit Silver",
    sub: "30fps 循环视频 · 撩发坐起",
    landscape: "assets/moonlit.jpg",
    portrait: "assets/moonlit-p.jpg",
    thumbL: "assets/moonlit-thumb.jpg",
    thumbP: "assets/moonlit-p-thumb.jpg",
    videoL: "assets/vid/moonlit-l.mp4",
    videoP: "assets/vid/moonlit-p.mp4",
    originL: "48% 36%",
    originP: "50% 34%",
    fx: "moonlit",
  },
];
