import { cssr, styles as sharedStyles } from 'dsh-tauri-ui/client'

const { c, bem: { b, e, m } } = cssr
const { primary, secondary, tertiary, borderL2: border, business, layer1, layer3, hover } = sharedStyles

export default b('extension', [
  e('section', {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    color: primary,
  }),
  e('intro', { margin: '0', fontSize: '12px', lineHeight: '18px', color: tertiary }),
  e('empty', { margin: '0', fontSize: '13px', lineHeight: '20px', color: tertiary }),
  e('spacer', { flex: '1' }),
  e('head', {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  }, [
    c('& h3', { margin: '0', fontSize: '16px', lineHeight: '24px', fontWeight: '500' }),
  ]),
  e('head-icon', {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 'none',
    width: '22px',
    height: '22px',
  }),
  e('list-head', {
    display: 'flex',
    alignItems: 'center',
    gap: '7px',
    padding: '0 2px',
    marginTop: '2px',
  }, [
    c('& h3', { margin: '0', fontSize: '13px', lineHeight: '20px', fontWeight: '600' }),
  ]),
  e('count', { fontSize: '12px', lineHeight: '18px', color: tertiary, fontVariantNumeric: 'tabular-nums' }),
  e('banner', {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
    border: `1px solid ${border}`,
    borderRadius: '8px',
    padding: '10px 12px',
    background: layer3,
    fontSize: '13px',
    lineHeight: '20px',
  }, [
    c('&[data-kind="ok"]', {
      borderColor: 'color-mix(in srgb,var(--dsw-alias-state-success-primary) 35%,transparent)',
      background: 'color-mix(in srgb,var(--dsw-alias-state-success-primary) 8%,transparent)',
    }),
    c('&[data-kind="error"]', {
      borderColor: 'color-mix(in srgb,var(--dsw-alias-state-error-primary) 35%,transparent)',
      background: 'color-mix(in srgb,var(--dsw-alias-state-error-primary) 8%,transparent)',
    }),
    c('&[data-kind="info"]', {
      borderColor: `color-mix(in srgb,${business} 35%,transparent)`,
      background: `color-mix(in srgb,${business} 8%,transparent)`,
    }),
  ]),
  e('banner-body', { flex: '1', minWidth: '0', display: 'flex', flexDirection: 'column', gap: '4px' }),
  e('banner-hint', {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
    color: secondary,
    fontSize: '12px',
    lineHeight: '18px',
  }),
  e('form', { display: 'flex', flexDirection: 'column', gap: '10px' }),
  e('label', {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    fontSize: '12px',
    lineHeight: '18px',
    color: secondary,
  }, [
    c('& > span:first-child', { color: tertiary }),
  ]),
  e('checks', {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    flexWrap: 'wrap',
  }),
  e('form-error', {
    margin: '0',
    color: 'var(--dsw-alias-state-error-primary)',
    fontSize: '12px',
    lineHeight: '18px',
  }),
  c('&.dshp-extension__modal-wide.dshp-extension__modal-wide', { width: 'min(680px,100%)' }),
  c('&.dshp-extension__modal-form.dshp-extension__modal-form', { width: 'min(760px,100%)' }),
  c('.dshp-extension__modal-scroll.dshp-extension__modal-scroll', { maxHeight: 'calc(100vh - 160px)', overflowY: 'auto' }),
  e('cards', {
    display: 'grid',
    gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
    alignItems: 'stretch',
    gap: '10px',
    margin: '0',
    padding: '0',
    listStyle: 'none',
  }, [
    m('single', { gridTemplateColumns: 'minmax(0,1fr)' }),
  ]),
  e('card', {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: '0',
    border: `1px solid ${border}`,
    borderRadius: '10px',
    background: layer3,
    padding: '12px 14px',
  }, [
    c('&:hover', { background: hover }),
    m('muted', { opacity: '.55' }),
  ]),
  e('card-top', { display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }),
  e('card-row', { display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }),
  e('card-title', {
    flex: '1',
    minWidth: '0',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '14px',
    lineHeight: '20px',
    fontWeight: '600',
    fontFamily: 'var(--ds-font-family-code)',
  }),
  e('card-desc', {
    margin: '0',
    fontSize: '12px',
    lineHeight: '18px',
    color: secondary,
    display: '-webkit-box',
    WebkitLineClamp: '2',
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  }),
  e('chips', { display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }),
  e('search', { width: '200px' }),
  // dsh-tauri-ui 无 Textarea 导出，多行正文/参数编辑器保留原生元素与自有外观。
  e('textarea', {
    width: '100%',
    boxSizing: 'border-box',
    border: `1px solid ${border}`,
    borderRadius: '8px',
    padding: '7px 10px',
    outline: 'none',
    background: layer1,
    color: primary,
    font: 'inherit',
    fontSize: '13px',
    minHeight: '320px',
    resize: 'vertical',
    fontFamily: 'var(--ds-font-family-code)',
    lineHeight: '1.5',
  }, [
    c('&[data-short="true"]', { minHeight: '96px' }),
    c('&:focus-visible', {
      borderColor: business,
      boxShadow: `0 0 0 2px color-mix(in srgb,${business} 18%,transparent)`,
    }),
  ]),
  e('json-editor', { minHeight: '260px' }),
  e('md-preview', {
    minHeight: '320px',
    maxHeight: '60vh',
    overflowY: 'auto',
    border: `1px solid ${border}`,
    borderRadius: '8px',
    padding: '8px 12px',
    background: layer1,
    fontSize: '13px',
  }),
  e('md-body', [
    c('& h1, & h2, & h3, & h4', { margin: '14px 0 6px', color: primary, lineHeight: '1.4' }),
    c('& h1', { fontSize: '18px' }),
    c('& h2', { fontSize: '16px' }),
    c('& h3', { fontSize: '14px' }),
    c('& h4', { fontSize: '13px' }),
    c('& p', { margin: '6px 0', lineHeight: '20px' }),
    c('& ul, & ol', { margin: '6px 0', paddingLeft: '20px' }),
    c('& code', {
      fontFamily: 'var(--ds-font-family-code)',
      fontSize: '12px',
      background: layer3,
      borderRadius: '4px',
      padding: '1px 5px',
    }),
    c('& pre', {
      margin: '8px 0',
      padding: '10px 12px',
      overflowX: 'auto',
      border: `1px solid ${border}`,
      borderRadius: '8px',
      background: layer3,
    }),
    c('& a', { color: business }),
  ]),
  e('tab-panel', { minWidth: '0', paddingTop: '2px' }),
  e('import-scroll', {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    maxHeight: 'min(400px,52vh)',
    overflowY: 'auto',
    padding: '2px 4px 2px 2px',
  }),
  e('import-group', { display: 'flex', flexDirection: 'column', gap: '8px' }),
  e('import-head', { display: 'flex', alignItems: 'center', gap: '8px', padding: '0 2px' }),
  e('import-count', { fontSize: '12px', lineHeight: '18px', color: tertiary }),
  e('import-all', { marginLeft: 'auto' }),
  c('@media (max-width: 680px)', [
    c('.dshp-extension__cards', { gridTemplateColumns: 'minmax(0,1fr)' }),
    c('.dshp-extension__search', { width: '140px' }),
  ]),
])
